import Navbar from "@/components/navbar";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Sendit Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
